import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { ATTRIBUTES, SKILLS, TRAINING_BONUS, creationPointsUsed, type CharacterSheetData, type OrdemAttribute, type TrainingLevel } from "@/data/ordemRules";
import { uid } from "@/lib/dice";
import { BookOpen, Crosshair, Dice5, Plus, Trash2 } from "lucide-react";

const SECTIONS = ["Identidade", "Conceito", "Atributos", "Recursos", "Perícias", "Ataques", "Poderes/Rituais", "Inventário"] as const;
type Section = typeof SECTIONS[number];

export function CharacterSheetPanel({ sheet, editable, saveStatus, onChange, onRollAttribute, onRollSkill, onRollAttack, onRollDamage }: {
  sheet: CharacterSheetData;
  editable: boolean;
  saveStatus: string;
  onChange: (next: CharacterSheetData) => void;
  onRollAttribute: (attr: OrdemAttribute) => void;
  onRollSkill: (skillId: string) => void;
  onRollAttack: (attackId: string) => void;
  onRollDamage: (attackId: string) => void;
}) {
  const [section, setSection] = useState<Section>("Identidade");
  const creation = useMemo(() => creationPointsUsed(sheet.attributes), [sheet.attributes]);
  const patch = (part: keyof CharacterSheetData, value: unknown) => onChange({ ...sheet, [part]: value });

  return <div className="space-y-4">
    <div className="flex flex-wrap items-center gap-2 rounded-sm border border-border bg-card/50 p-3">
      <div><p className="stamp text-primary">Ficha de personagem</p><p className="font-semibold">{sheet.identity.name || "Agente sem nome"}</p></div>
      <span className={`ml-auto stamp text-[10px] ${saveStatus.includes("erro") ? "text-destructive" : "text-route-verde-claro"}`}>{saveStatus}</span>
    </div>
    <nav className="flex gap-1 overflow-x-auto pb-1">{SECTIONS.map(s=><button key={s} className={`shrink-0 rounded-sm px-3 py-2 text-xs ${section===s?"bg-primary text-primary-foreground":"bg-secondary text-muted-foreground"}`} onClick={()=>setSection(s)}>{s}</button>)}</nav>

    {section==="Identidade"&&<Panel title="Identidade"><div className="grid gap-3 md:grid-cols-2"><TextField label="Nome do personagem" value={sheet.identity.name} editable={editable} onChange={v=>patch("identity",{...sheet.identity,name:v})}/><TextField label="Idade" value={sheet.identity.age} editable={editable} onChange={v=>patch("identity",{...sheet.identity,age:v})}/><TextField label="URL da imagem/avatar" value={sheet.identity.avatarUrl} editable={editable} onChange={v=>patch("identity",{...sheet.identity,avatarUrl:v})}/></div><LongField label="Aparência" value={sheet.identity.appearance} editable={editable} onChange={v=>patch("identity",{...sheet.identity,appearance:v})}/><LongField label="Personalidade" value={sheet.identity.personality} editable={editable} onChange={v=>patch("identity",{...sheet.identity,personality:v})}/><LongField label="Histórico" value={sheet.identity.history} editable={editable} onChange={v=>patch("identity",{...sheet.identity,history:v})}/><LongField label="Objetivo" value={sheet.identity.objective} editable={editable} onChange={v=>patch("identity",{...sheet.identity,objective:v})}/></Panel>}

    {section==="Conceito"&&<Panel title="Conceito e progressão"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><TextField label="Origem" value={sheet.concept.origin} editable={editable} onChange={v=>patch("concept",{...sheet.concept,origin:v})}/><div><Label>Classe</Label><select disabled={!editable} className="mt-1 w-full rounded-sm border border-input bg-background p-2 text-sm" value={sheet.concept.className} onChange={e=>patch("concept",{...sheet.concept,className:e.target.value as CharacterSheetData["concept"]["className"]})}><option>Combatente</option><option>Especialista</option><option>Ocultista</option><option>Custom</option></select></div>{sheet.concept.className==="Custom"&&<TextField label="Classe custom" value={sheet.concept.customClass} editable={editable} onChange={v=>patch("concept",{...sheet.concept,customClass:v})}/>}<TextField label="Trilha" value={sheet.concept.trail} editable={editable} onChange={v=>patch("concept",{...sheet.concept,trail:v})}/><NumField label="NEX %" value={sheet.concept.nex} editable={editable} onChange={v=>patch("concept",{...sheet.concept,nex:v})}/><TextField label="Patente" value={sheet.concept.rank} editable={editable} onChange={v=>patch("concept",{...sheet.concept,rank:v})}/><NumField label="Deslocamento" value={sheet.concept.movement} editable={editable} onChange={v=>patch("concept",{...sheet.concept,movement:v})}/><NumField label="PE por rodada" value={sheet.concept.pePerRound} editable={editable} onChange={v=>patch("concept",{...sheet.concept,pePerRound:v})}/></div><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" disabled={!editable} checked={sheet.concept.freeMode} onChange={e=>patch("concept",{...sheet.concept,freeMode:e.target.checked})}/>Modo livre/homebrew — permite ultrapassar recomendações de criação</label></Panel>}

    {section==="Atributos"&&<Panel title="Atributos"><div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{ATTRIBUTES.map(a=><div key={a.id} className="rounded-sm border border-border p-3 text-center"><p className="stamp text-muted-foreground">{a.id}</p><p className="text-xs">{a.label}</p><Input disabled={!editable} type="number" min={sheet.concept.freeMode?-5:0} max={sheet.concept.freeMode?20:3} value={sheet.attributes[a.id]} onChange={e=>patch("attributes",{...sheet.attributes,[a.id]:Number(e.target.value)})} className="mx-auto mt-2 w-20 text-center text-xl"/><Button size="sm" variant="outline" className="mt-2 w-full" onClick={()=>onRollAttribute(a.id)}><Dice5 className="mr-1 size-3.5"/>Rolar</Button></div>)}</div><div className={`mt-4 rounded-sm border p-3 text-sm ${sheet.concept.freeMode||creation.valid?"border-route-verde/40":"border-route-amarelo/60"}`}><b>Criação base:</b> {creation.spent}/{creation.budget} pontos usados. Atributos iniciam em 1; reduzir um para 0 aumenta o orçamento em 1; limite inicial recomendado 3. {sheet.concept.freeMode&&<span className="text-muted-foreground"> Modo livre ativo.</span>}</div></Panel>}

    {section==="Recursos"&&<Panel title="Recursos e defesa"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><ResourcePair label="PV" current={sheet.resources.pv} max={sheet.resources.pvMax} editable={editable} onChange={(current,max)=>patch("resources",{...sheet.resources,pv:current,pvMax:max})}/><ResourcePair label="PE" current={sheet.resources.pe} max={sheet.resources.peMax} editable={editable} onChange={(current,max)=>patch("resources",{...sheet.resources,pe:current,peMax:max})}/><ResourcePair label="SAN" current={sheet.resources.san} max={sheet.resources.sanMax} editable={editable} onChange={(current,max)=>patch("resources",{...sheet.resources,san:current,sanMax:max})}/><NumField label="Defesa" value={sheet.resources.defense} editable={editable} onChange={v=>patch("resources",{...sheet.resources,defense:v})}/><TextField label="Proteção" value={sheet.resources.protection} editable={editable} onChange={v=>patch("resources",{...sheet.resources,protection:v})}/><TextField label="Resistências" value={sheet.resources.resistances} editable={editable} onChange={v=>patch("resources",{...sheet.resources,resistances:v})}/><ResourcePair label="Carga / espaços" current={sheet.resources.load} max={sheet.resources.loadMax} editable={editable} onChange={(current,max)=>patch("resources",{...sheet.resources,load:current,loadMax:max})}/><TextField label="Crédito" value={sheet.resources.credit} editable={editable} onChange={v=>patch("resources",{...sheet.resources,credit:v})}/><NumField label="Prestígio" value={sheet.resources.prestige} editable={editable} onChange={v=>patch("resources",{...sheet.resources,prestige:v})}/></div></Panel>}

    {section==="Perícias"&&<Panel title="Perícias"><div className="space-y-2">{SKILLS.map(skill=>{const s=sheet.skills[skill.id]??{training:"DESTREINADO" as TrainingLevel,otherBonus:0};const total=TRAINING_BONUS[s.training]+Number(s.otherBonus||0);return <div key={skill.id} className="grid grid-cols-[minmax(100px,1fr)_58px] items-center gap-2 rounded-sm border border-border p-2 sm:grid-cols-[minmax(140px,1fr)_70px_130px_90px_85px]"><div><b>{skill.id==="profissao"&&s.customName?s.customName:skill.name}</b><span className="ml-2 stamp text-[10px] text-muted-foreground">{skill.attribute}</span>{skill.id==="profissao"&&editable&&<Input className="mt-1 h-7" placeholder="Nome da profissão" value={s.customName??""} onChange={e=>patch("skills",{...sheet.skills,[skill.id]:{...s,customName:e.target.value}})}/>}</div><b className="text-right sm:text-left">+{total}</b><select disabled={!editable} className="hidden rounded-sm border border-input bg-background p-1.5 text-xs sm:block" value={s.training} onChange={e=>patch("skills",{...sheet.skills,[skill.id]:{...s,training:e.target.value as TrainingLevel}})}><option value="DESTREINADO">Destreinado 0</option><option value="TREINADO">Treinado +5</option><option value="VETERANO">Veterano +10</option><option value="EXPERT">Expert +15</option></select><Input disabled={!editable} className="hidden h-8 sm:block" type="number" value={s.otherBonus} onChange={e=>patch("skills",{...sheet.skills,[skill.id]:{...s,otherBonus:Number(e.target.value)}})}/><Button size="sm" variant="outline" className="col-span-2 sm:col-span-1" onClick={()=>onRollSkill(skill.id)}><Dice5 className="mr-1 size-3.5"/>Rolar</Button></div>})}</div></Panel>}

    {section==="Ataques"&&<Panel title="Ataques"><div className="space-y-3">{sheet.attacks.map(atk=><div key={atk.id} className="rounded-sm border border-border p-3"><div className="flex flex-wrap items-center gap-2"><Input disabled={!editable} className="min-w-[160px] flex-1 font-semibold" value={atk.name} onChange={e=>patch("attacks",sheet.attacks.map(a=>a.id===atk.id?{...a,name:e.target.value}:a))}/>{editable&&<Button size="sm" variant="ghost" onClick={()=>patch("attacks",sheet.attacks.filter(a=>a.id!==atk.id))}><Trash2 className="size-4"/></Button>}</div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><SelectAttr value={atk.attribute} editable={editable} onChange={v=>patch("attacks",sheet.attacks.map(a=>a.id===atk.id?{...a,attribute:v}:a))}/><TextField label="Perícia" value={atk.skillId} editable={editable} onChange={v=>patch("attacks",sheet.attacks.map(a=>a.id===atk.id?{...a,skillId:v}:a))}/><NumField label="Bônus" value={atk.bonus} editable={editable} onChange={v=>patch("attacks",sheet.attacks.map(a=>a.id===atk.id?{...a,bonus:v}:a))}/><TextField label="Dano" value={atk.damage} editable={editable} onChange={v=>patch("attacks",sheet.attacks.map(a=>a.id===atk.id?{...a,damage:v}:a))}/><NumField label="Margem crítica" value={atk.criticalMargin} editable={editable} onChange={v=>patch("attacks",sheet.attacks.map(a=>a.id===atk.id?{...a,criticalMargin:v}:a))}/><NumField label="Multiplicador" value={atk.criticalMultiplier} editable={editable} onChange={v=>patch("attacks",sheet.attacks.map(a=>a.id===atk.id?{...a,criticalMultiplier:v}:a))}/><TextField label="Alcance" value={atk.range} editable={editable} onChange={v=>patch("attacks",sheet.attacks.map(a=>a.id===atk.id?{...a,range:v}:a))}/><TextField label="Munição" value={atk.ammo} editable={editable} onChange={v=>patch("attacks",sheet.attacks.map(a=>a.id===atk.id?{...a,ammo:v}:a))}/></div><LongField label="Especial / notas" value={atk.special} editable={editable} onChange={v=>patch("attacks",sheet.attacks.map(a=>a.id===atk.id?{...a,special:v}:a))}/><div className="mt-2 flex gap-2"><Button size="sm" onClick={()=>onRollAttack(atk.id)}><Crosshair className="mr-1 size-3.5"/>Rolar ataque</Button><Button size="sm" variant="secondary" onClick={()=>onRollDamage(atk.id)}><Dice5 className="mr-1 size-3.5"/>Rolar dano</Button></div></div>)}{sheet.attacks.length===0&&<Empty text="Nenhum ataque cadastrado."/>}{editable&&<Button variant="outline" onClick={()=>patch("attacks",[...sheet.attacks,{id:uid("atk"),name:"Novo ataque",attribute:"FOR",skillId:"luta",bonus:0,damage:"1d6",criticalMargin:20,criticalMultiplier:2,range:"",special:"",ammo:""}])}><Plus className="mr-1 size-4"/>Adicionar ataque</Button>}</div></Panel>}

    {section==="Poderes/Rituais"&&<Panel title="Habilidades, poderes e rituais"><p className="mb-3 text-xs text-muted-foreground">Cards livres para registrar o que existe na ficha. O site não embute descrições extensas do livro.</p><div className="space-y-3">{sheet.abilities.map(ab=><div key={ab.id} className="rounded-sm border border-border p-3"><div className="flex gap-2"><Input disabled={!editable} className="font-semibold" value={ab.name} onChange={e=>patch("abilities",sheet.abilities.map(a=>a.id===ab.id?{...a,name:e.target.value}:a))}/>{editable&&<Button size="sm" variant="ghost" onClick={()=>patch("abilities",sheet.abilities.filter(a=>a.id!==ab.id))}><Trash2 className="size-4"/></Button>}</div><div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><NumField label="Custo PE" value={ab.costPe} editable={editable} onChange={v=>patch("abilities",sheet.abilities.map(a=>a.id===ab.id?{...a,costPe:v}:a))}/><TextField label="Tipo" value={ab.type} editable={editable} onChange={v=>patch("abilities",sheet.abilities.map(a=>a.id===ab.id?{...a,type:v}:a))}/><TextField label="Círculo" value={ab.circle} editable={editable} onChange={v=>patch("abilities",sheet.abilities.map(a=>a.id===ab.id?{...a,circle:v}:a))}/><TextField label="Elemento" value={ab.element} editable={editable} onChange={v=>patch("abilities",sheet.abilities.map(a=>a.id===ab.id?{...a,element:v}:a))}/></div><LongField label="Resumo" value={ab.summary} editable={editable} onChange={v=>patch("abilities",sheet.abilities.map(a=>a.id===ab.id?{...a,summary:v}:a))}/>{ab.costPe>0&&<Button size="sm" variant="secondary" onClick={()=>patch("resources",{...sheet.resources,pe:Math.max(0,sheet.resources.pe-ab.costPe)})}>Gastar {ab.costPe} PE</Button>}</div>)}{sheet.abilities.length===0&&<Empty text="Nenhuma habilidade registrada."/>}{editable&&<Button variant="outline" onClick={()=>patch("abilities",[...sheet.abilities,{id:uid("ab"),name:"Nova habilidade",costPe:0,type:"",circle:"",element:"",summary:""}])}><Plus className="mr-1 size-4"/>Adicionar card</Button>}</div></Panel>}

    {section==="Inventário"&&<Panel title="Inventário"><div className="mb-3 flex items-center gap-3"><BookOpen className="size-4"/><span className="text-sm">Carga cadastrada: <b>{sheet.inventory.reduce((sum,i)=>sum+(Number(i.spaces)||0)*(Number(i.quantity)||0),0)}</b> espaços</span></div><div className="space-y-2">{sheet.inventory.map(item=><div key={item.id} className="grid gap-2 rounded-sm border border-border p-3 sm:grid-cols-2 lg:grid-cols-6"><Input disabled={!editable} value={item.name} onChange={e=>patch("inventory",sheet.inventory.map(i=>i.id===item.id?{...i,name:e.target.value}:i))} placeholder="Item"/><Input disabled={!editable} value={item.category} onChange={e=>patch("inventory",sheet.inventory.map(i=>i.id===item.id?{...i,category:e.target.value}:i))} placeholder="Categoria"/><Input disabled={!editable} type="number" value={item.spaces} onChange={e=>patch("inventory",sheet.inventory.map(i=>i.id===item.id?{...i,spaces:Number(e.target.value)}:i))} placeholder="Espaços"/><Input disabled={!editable} type="number" value={item.quantity} onChange={e=>patch("inventory",sheet.inventory.map(i=>i.id===item.id?{...i,quantity:Number(e.target.value)}:i))} placeholder="Qtd"/><label className="flex items-center gap-2 text-xs"><input type="checkbox" disabled={!editable} checked={item.equipped} onChange={e=>patch("inventory",sheet.inventory.map(i=>i.id===item.id?{...i,equipped:e.target.checked}:i))}/>Equipado</label><div className="flex gap-1"><Input disabled={!editable} value={item.notes} onChange={e=>patch("inventory",sheet.inventory.map(i=>i.id===item.id?{...i,notes:e.target.value}:i))} placeholder="Notas"/>{editable&&<Button size="sm" variant="ghost" onClick={()=>patch("inventory",sheet.inventory.filter(i=>i.id!==item.id))}><Trash2 className="size-4"/></Button>}</div></div>)}{sheet.inventory.length===0&&<Empty text="Inventário vazio."/>}{editable&&<Button variant="outline" onClick={()=>patch("inventory",[...sheet.inventory,{id:uid("item"),name:"",category:"",spaces:1,quantity:1,equipped:false,notes:""}])}><Plus className="mr-1 size-4"/>Adicionar item</Button>}</div></Panel>}
  </div>;
}

function Panel({title,children}:{title:string;children:React.ReactNode}) { return <section className="rounded-sm border border-border bg-card/35 p-4 sm:p-5"><h2 className="font-display text-2xl">{title}</h2><div className="mt-4 space-y-3">{children}</div></section>; }
function TextField({label,value,editable,onChange}:{label:string;value:string;editable:boolean;onChange:(v:string)=>void}) { return <div><Label>{label}</Label><Input className="mt-1" disabled={!editable} value={value} onChange={e=>onChange(e.target.value)}/></div>; }
function NumField({label,value,editable,onChange}:{label:string;value:number;editable:boolean;onChange:(v:number)=>void}) { return <div><Label>{label}</Label><Input className="mt-1" disabled={!editable} type="number" value={value} onChange={e=>onChange(Number(e.target.value))}/></div>; }
function LongField({label,value,editable,onChange}:{label:string;value:string;editable:boolean;onChange:(v:string)=>void}) { return <div><Label>{label}</Label><Textarea className="mt-1" disabled={!editable} value={value} onChange={e=>onChange(e.target.value)}/></div>; }
function ResourcePair({label,current,max,editable,onChange}:{label:string;current:number;max:number;editable:boolean;onChange:(c:number,m:number)=>void}) { return <div><Label>{label}</Label><div className="mt-1 grid grid-cols-[1fr_auto_1fr] items-center gap-1"><Input disabled={!editable} type="number" value={current} onChange={e=>onChange(Number(e.target.value),max)}/><span>/</span><Input disabled={!editable} type="number" value={max} onChange={e=>onChange(current,Number(e.target.value))}/></div></div>; }
function SelectAttr({value,editable,onChange}:{value:OrdemAttribute;editable:boolean;onChange:(v:OrdemAttribute)=>void}) { return <div><Label>Atributo</Label><select disabled={!editable} className="mt-1 w-full rounded-sm border border-input bg-background p-2 text-sm" value={value} onChange={e=>onChange(e.target.value as OrdemAttribute)}>{ATTRIBUTES.map(a=><option key={a.id} value={a.id}>{a.id} — {a.label}</option>)}</select></div>; }
function Empty({text}:{text:string}) { return <p className="rounded-sm border border-dashed border-border p-4 text-sm text-muted-foreground">{text}</p>; }
