/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaisRouteImport } from './routes/locais'
import { Route as PistasRouteImport } from './routes/pistas'
import { Route as SessaoRouteImport } from './routes/sessao'
import { Route as TimelineRouteImport } from './routes/timeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaisRoute = LocaisRouteImport.update({
  id: '/locais',
  path: '/locais',
  getParentRoute: () => rootRouteImport,
} as any)
const PistasRoute = PistasRouteImport.update({
  id: '/pistas',
  path: '/pistas',
  getParentRoute: () => rootRouteImport,
} as any)
const SessaoRoute = SessaoRouteImport.update({
  id: '/sessao',
  path: '/sessao',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/locais': typeof LocaisRoute
  '/pistas': typeof PistasRoute
  '/sessao': typeof SessaoRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/locais': typeof LocaisRoute
  '/pistas': typeof PistasRoute
  '/sessao': typeof SessaoRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/locais': typeof LocaisRoute
  '/pistas': typeof PistasRoute
  '/sessao': typeof SessaoRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/locais' | '/pistas' | '/sessao' | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/locais' | '/pistas' | '/sessao' | '/timeline'
  id: '__root__' | '/' | '/locais' | '/pistas' | '/sessao' | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaisRoute: typeof LocaisRoute
  PistasRoute: typeof PistasRoute
  SessaoRoute: typeof SessaoRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locais': {
      id: '/locais'
      path: '/locais'
      fullPath: '/locais'
      preLoaderRoute: typeof LocaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pistas': {
      id: '/pistas'
      path: '/pistas'
      fullPath: '/pistas'
      preLoaderRoute: typeof PistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessao': {
      id: '/sessao'
      path: '/sessao'
      fullPath: '/sessao'
      preLoaderRoute: typeof SessaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaisRoute: LocaisRoute,
  PistasRoute: PistasRoute,
  SessaoRoute: SessaoRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
